In [2]:
from scipy.spatial.transform import Rotation as R
import numpy as np

In [3]:
def transform_degree_to_quat(degree, direction):
        """Next try is to calculate the values according to the tutorials formula:
        Form:
        quat = [x, y, z, w]
        degree = [x_degree, y_degree, z_degree]
        direction = [x_dir, y_dir, z_dir]
        Example: rotate 45 degrees around x, y, z axis(direction: -x, -y, z)
        x = RotationAxis.x * sin(RotationAngle / 2) => -1 * sin( (1/4 * pi) / 2 ) = -0,382
        y = RotationAxis.y * sin(RotationAngle / 2) => -1 * sin( (1/4 * pi) / 2 ) = -0,382
        z = RotationAxis.z * sin(RotationAngle / 2) => 1 * sin( (1/4 * pi) / 2 ) = 0,382
        w = cos( (1/4 * pi) / 2) = 0,923"""
        quat = np.zeros(4)
        # transform degree to radian
        radian = np.radians(degree)
        # calculate the values
        quat[0] = direction[0] * np.sin(radian[0] / 2)
        quat[1] = direction[1] * np.sin(radian[1] / 2)
        quat[2] = direction[2] * np.sin(radian[2] / 2)
        quat[3] = np.cos(radian[0] / 2)
        return quat

In [4]:
def transform_quat_to_degree(quat):
        """Transform the quaternion to degree
        Form:
        quat = [x, y, z, w]
        degree = [x_degree, y_degree, z_degree]
        direction = [x_dir, y_dir, z_dir]
        """
        degree = np.zeros(3)
        # calculate the values
        degree[0] = np.degrees(np.arctan2(2 * (quat[3] * quat[0] + quat[1] * quat[2]), 1 - 2 * (quat[0] ** 2 + quat[1] ** 2)))
        degree[1] = np.degrees(np.arcsin(2 * (quat[3] * quat[1] - quat[2] * quat[0])))
        degree[2] = np.degrees(np.arctan2(2 * (quat[3] * quat[2] + quat[0] * quat[1]), 1 - 2 * (quat[1] ** 2 + quat[2] ** 2)))
        return degree

In [12]:
r1 = R.from_rotvec([0, 0, 0])
#r = r1.from_rotvec([0, 0, np.pi/2])
#r = r1.from_rotvec([0, np.pi/2, 0])
r = r1.from_rotvec([np.pi/2,0, 0])
#r = r.from_rotvec([0, np.pi/5, 0])
#r = r1.from_rotvec([0, np.pi/6, 0])
print(r.as_euler('xyz', degrees=True))
print(r.as_euler('xyz', degrees=True).shape)
print(r.as_quat())
quat = transform_degree_to_quat(r.as_euler('xyz', degrees=True), [1, 1, 1])
print(quat)
degree = transform_quat_to_degree(quat)
print(degree)

r = r1.from_quat([-0.087 ,0 ,0, 0.996])
degree = r.as_euler('xyz', degrees=True)
print(degree)

r = r1.from_euler('xyz', [45, 45, 45], degrees=True)
print(r.as_quat(scalar_first=True))
print(r.as_euler('xyz', degrees=True))



[90.  0.  0.]
(3,)
[0.70710678 0.         0.         0.70710678]
[0.70710678 0.         0.         0.70710678]
[90.  0.  0.]
[-9.98416233  0.          0.        ]
[0.8446232  0.19134172 0.46193977 0.19134172]
[45. 45. 45.]


In [6]:
# initial rotation as 0, 0, 0
r = r1.from_euler('xyz', [88, 45, 30], degrees=True)
print(r.as_euler('xyz', degrees=True))
print(r.as_quat())
quat = transform_degree_to_quat(r.as_euler('xyz', degrees=True), [1, 1, 1])
print(quat)
degree = transform_quat_to_degree(r.as_quat())
print(degree)

[88. 45. 30.]
[ 0.54866495  0.43200456 -0.08476935  0.71074116]
[0.69465837 0.38268343 0.25881905 0.7193398 ]
[88. 45. 30.]


In [7]:
r = r1.from_euler('xyz', [[90, 45, 30], [35, 45, 90]], degrees=True)
print(r.as_euler('xyz', degrees=True))
print(r.as_quat())
quat = transform_degree_to_quat(r.as_euler('xyz', degrees=True), [1, 1, 1])
print(quat)
degree = transform_quat_to_degree(quat)
print(degree)

[[90. 45. 30.]
 [35. 45. 90.]]
[[ 0.56098553  0.43045933 -0.09229596  0.70105738]
 [-0.06162842  0.45451948  0.54167522  0.70441603]]


ValueError: setting an array element with a sequence.

In [35]:
r = r1.from_euler('z', 90, degrees=True)
print(r.as_euler('xyz', degrees=True))
print(r.as_matrix())

[ 0.  0. 90.]
[[ 2.22044605e-16 -1.00000000e+00  0.00000000e+00]
 [ 1.00000000e+00  2.22044605e-16  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]
