In [1]:
from scipy.spatial.transform import Rotation as R
import numpy as np

In [2]:
def transform_degree_to_quat(degree, direction):
        """Next try is to calculate the values according to the tutorials formula:
        Form:
        quat = [x, y, z, w]
        degree = [x_degree, y_degree, z_degree]
        direction = [x_dir, y_dir, z_dir]
        Example: rotate 45 degrees around x, y, z axis(direction: -x, -y, z)
        x = RotationAxis.x * sin(RotationAngle / 2) => -1 * sin( (1/4 * pi) / 2 ) = -0,382
        y = RotationAxis.y * sin(RotationAngle / 2) => -1 * sin( (1/4 * pi) / 2 ) = -0,382
        z = RotationAxis.z * sin(RotationAngle / 2) => 1 * sin( (1/4 * pi) / 2 ) = 0,382
        w = cos( (1/4 * pi) / 2) = 0,923"""
        quat = np.zeros(4)
        # transform degree to radian
        radian = np.radians(degree)
        # calculate the values
        quat[0] = direction[0] * np.sin(radian[0] / 2)
        quat[1] = direction[1] * np.sin(radian[1] / 2)
        quat[2] = direction[2] * np.sin(radian[2] / 2)
        quat[3] = np.cos(radian[0] / 2)
        return quat

In [3]:
def transform_quat_to_degree(quat):
        """Transform the quaternion to degree
        Form:
        quat = [x, y, z, w]
        degree = [x_degree, y_degree, z_degree]
        direction = [x_dir, y_dir, z_dir]
        """
        degree = np.zeros(3)
        # calculate the values
        degree[0] = np.degrees(np.arctan2(2 * (quat[3] * quat[0] + quat[1] * quat[2]), 1 - 2 * (quat[0] ** 2 + quat[1] ** 2)))
        degree[1] = np.degrees(np.arcsin(2 * (quat[3] * quat[1] - quat[2] * quat[0])))
        degree[2] = np.degrees(np.arctan2(2 * (quat[3] * quat[2] + quat[0] * quat[1]), 1 - 2 * (quat[1] ** 2 + quat[2] ** 2)))
        return degree

In [4]:
r1 = R.from_rotvec([0, 0, 0])
#r = r1.from_rotvec([0, 0, np.pi/2])
#r = r1.from_rotvec([0, np.pi/2, 0])
r = r1.from_rotvec([np.pi/2,0, 0])
#r = r.from_rotvec([0, np.pi/5, 0])
#r = r1.from_rotvec([0, np.pi/6, 0])
print(r.as_euler('xyz', degrees=True))
print(r.as_euler('xyz', degrees=True).shape)
print(r.as_quat())
quat = transform_degree_to_quat(r.as_euler('xyz', degrees=True), [1, 1, 1])
print(quat)
degree = transform_quat_to_degree(quat)
print(degree)

r = r1.from_quat([-0.087 ,0 ,0, 0.996])
degree = r.as_euler('xyz', degrees=True)
print(degree)

r = r1.from_euler('xyz', [45, 45, 45], degrees=True)
print(r.as_quat(scalar_first=True))
print(r.as_euler('xyz', degrees=True))



[90.  0.  0.]
(3,)
[0.70710678 0.         0.         0.70710678]
[0.70710678 0.         0.         0.70710678]
[90.  0.  0.]
[-9.98416233  0.          0.        ]
[0.8446232  0.19134172 0.46193977 0.19134172]
[45. 45. 45.]


In [5]:
# initial rotation as 0, 0, 0
r = r1.from_euler('xyz', [88, 45, 30], degrees=True)
print(r.as_euler('xyz', degrees=True))
print(r.as_quat())
quat = transform_degree_to_quat(r.as_euler('xyz', degrees=True), [1, 1, 1])
print(quat)
degree = transform_quat_to_degree(r.as_quat())
print(degree)

[88. 45. 30.]
[ 0.54866495  0.43200456 -0.08476935  0.71074116]
[0.69465837 0.38268343 0.25881905 0.7193398 ]
[88. 45. 30.]


In [28]:
root = [0.4,-0.2,0.25]
r_0 = r1.from_euler('xyz', [0,0,0], degrees=False)
r_1 = r1.from_euler('xyz', [0,0,0], degrees=False)
r_2 = r1.from_euler('xyz', [0,0,0], degrees=False)
r_3 = r1.from_euler('xyz', [0,0.1*np.pi,0], degrees=False)
r_4 = r1.from_euler('xyz', [0,0.2*np.pi,0], degrees=False)
r_5 = r1.from_euler('xyz', [0,0.3*np.pi,0], degrees=False)
r_6 = r1.from_euler('xyz', [0,0.5*np.pi,0], degrees=False)
obs_1 = [0,0,-0.07]
par_1 = [0,0,0.25]
obs_2 = [0,0,0]
par_2 = [0,0,0.07]
obs_3 = [0,0,-0.2]
par_3 = [0,0.18,0.2]
obs_4 = [0,0,-0.18]
par_4 = [0,0,0.2]
obs_5 = [0,0,0.2]
par_5 = [0,-0.19,0.2]
obs_6 = [0,0,0.18]
par_6 = [0,0,-0.2]
obs_ref_1 = r_1.apply(obs_1)
obs_ref_2 = r_2.apply(obs_2)
obs_ref_3 = r_3.apply(obs_3) 
obs_ref_4 = r_4.apply(obs_4)
obs_ref_5 = r_5.apply(obs_5)
obs_ref_6 = r_6.apply(obs_6)

par_ref_1 = r_0.apply(par_1) + root
par_ref_3 = r_0.apply(par_3) + root
par_ref_5 = r_0.apply(par_5) + root

def_1 = par_ref_1 - obs_ref_1
def_3 = par_ref_3 - obs_ref_3
def_5 = par_ref_5 - obs_ref_5

par_ref_2 = r_1.apply(par_2) + def_1
par_ref_4 = r_3.apply(par_4) + def_3
par_ref_6 = r_5.apply(par_6) + def_5

def_2 = par_ref_2 - obs_ref_2
def_4 = par_ref_4 - obs_ref_4
def_6 = par_ref_6 - obs_ref_6
#def_3 = obs_ref_3 - par_ref_3
print(obs_ref_1)
print(obs_ref_3)
print(obs_ref_5)
print(obs_ref_2)
print(obs_ref_4)
print(obs_ref_6)
print("------------------------")
print(par_ref_1)
print(par_ref_3)
print(par_ref_5)
print(par_ref_2)
print(par_ref_4)
print(par_ref_6)
print("------------------------")
print(def_1)
print(def_3)
print(def_5)
print(def_2)
print(def_4)
print(def_6)

[ 0.    0.   -0.07]
[-0.0618034  0.        -0.1902113]
[0.1618034  0.         0.11755705]
[0. 0. 0.]
[-0.10580135  0.         -0.14562306]
[1.80000000e-01 0.00000000e+00 3.99680289e-17]
------------------------
[ 0.4 -0.2  0.5]
[ 0.4  -0.02  0.45]
[ 0.4  -0.39  0.45]
[ 0.4  -0.2   0.64]
[ 0.5236068  -0.02        0.83042261]
[ 0.0763932 -0.39       0.2148859]
------------------------
[ 0.4  -0.2   0.57]
[ 0.4618034 -0.02       0.6402113]
[ 0.2381966  -0.39        0.33244295]
[ 0.4  -0.2   0.64]
[ 0.62940814 -0.02        0.97604567]
[-0.1036068 -0.39       0.2148859]


In [7]:
r = r1.from_euler('xyz', [[90, 45, 30], [35, 45, 90]], degrees=True)
print(r.as_euler('xyz', degrees=True))
print(r.as_quat())
quat = transform_degree_to_quat(r.as_euler('xyz', degrees=True), [1, 1, 1])
print(quat)
degree = transform_quat_to_degree(quat)
print(degree)

[[90. 45. 30.]
 [35. 45. 90.]]
[[ 0.56098553  0.43045933 -0.09229596  0.70105738]
 [-0.06162842  0.45451948  0.54167522  0.70441603]]


ValueError: setting an array element with a sequence.

In [35]:
r = r1.from_euler('z', 90, degrees=True)
print(r.as_euler('xyz', degrees=True))
print(r.as_matrix())

[ 0.  0. 90.]
[[ 2.22044605e-16 -1.00000000e+00  0.00000000e+00]
 [ 1.00000000e+00  2.22044605e-16  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]
